project_id = "vbexqyglhfppxlhwlbes"

[functions.extract-url-info]
verify_jwt = false

[functions.send-feedback]
verify_jwt = false

[functions.mcp-server]
verify_jwt = false

[functions.notify-comment]
verify_jwt = false